config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :questions do
    resources :answers
  end
  resources :users
  root 'questions#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  validates :description, presence: true, length: { minimum: 50 }

  belongs_to :question
  belongs_to :user

  default_scope { order('rating DESC') }
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 40}
  validates :description, presence: true, length: { minimum: 150}

  has_many :answers, dependent: :destroy
  belongs_to :user

  default_scope { order('updated_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    find_or_initialize_by(provider: auth.provider, uid: auth.uid) do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.image = auth.info.image
      user.save!
    end
  end
  has_many :questions
  has_many :answers, through: :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id if current_user
    @answer.question_id = @question.id

    if @answer.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.rating.nil?
      @answer.update_attribute(:rating, 1)
    else
      num = @answer.rating + 1
      @answer.update_attribute(:rating, num)
    end

    redirect_to @question
  end

  private
  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  helper_method :current_user


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id if current_user

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :description, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def user_params
    params.require(:user).permit(:provider, :uid, :name, :oauth_token, :oauth_expires_at, :image)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
class CodeRayify < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div
  end
end

def markdown(text)
  coderayified = CodeRayify.new(:filter_html => true,
                                :hard_wrap => true)
  options = {
    :fenced_code_blocks => true,
    :no_intra_emphasis => true,
    :autolink => true,
    :strikethrough => true,
    :lax_html_blocks => true,
    :superscript => true
  }
  markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
  markdown_to_html.render(text).html_safe
end
end

app/helpers/question_helper.rb
module QuestionHelper

end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @answer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/new.html.erb
<h1> Answer Question: </h1>
<strong><%= @question.title %><br></strong>
<%= @question.description %>

<h1> What is your brilliant answer? </h1>

<%= render 'answers/form', question: @question, answer: @answer %>

app/views/answers/show.html.erb
<h1> Test </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
    <%= yield %>
  <% else %>
    <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
  <% end %>
</ul>



</body>
</html>

app/views/questions/_form.html.erb
<%= form_for question do |f| %>
  <% if question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(question.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1> Edit Question </h1>

<%= render 'questions/form', question: @question %>

app/views/questions/index.html.erb
<h1> Questions </h1>

<%= link_to "New Question", new_question_path %>
<ul>
  <% @questions.each do |question| %>
    <li> <%= link_to question.title, question_path(question) %> </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1> Create New Question </h1>

<%= render 'questions/form', question: @question %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%= markdown(@question.description) %>

<h2> Posted by: <%= @question.user.name %> </h2>

<%= link_to "Answer", new_question_answer_path(@question) %>


<% if current_user.id == @question.user_id %>
  <%= link_to "Edit Question", edit_question_path %>
  <%= link_to "Delete Question", question_path %>
<% end %>
<%= link_to "Home", root_path %>

<% if !@answers.empty? %>
<p></p>
<ul>
  <% @answers.each do |answer| %>
    <li><%= link_to "Vote Best Answer", question_answer_path(@question, answer), method: :patch %>: <%= answer.rating %> <strong><%= answer.user.name %> says:</strong> <%= markdown(answer.description) %> </li>
  <% end %>
</ul>
<% end %>